fixed

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -60,4 +60,25 @@ jobs:
         run: |
           ssh -o StrictHostKeyChecking=no -i private-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/URL-shortener && pm2 restart url-shortener"
 
+  verify_deploy:
+    name: Verify Deployment
+    runs-on: ubuntu-latest
+    needs: deploy 
+
+    steps:
+    - name: Verify Deployment
+      uses: peterkimzz/aws-ssm-send-command@master
+      with:
+        aws-region: ${{ secrets.AWS_REGION }}
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
+        commands: |
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
+          if [ "$STATUS" -eq 200 ]; then
+            echo "Deployment successful"
+          else
+            echo "Deployment failed"
+            exit 1
+          fi
 
